erpnext_documentation/www/docs/user/manual/en/setting-up/stock-reconciliation.md

Updated links to point to correct image links

docs: fix images for stock reco

---

erpnext_documentation/www/docs/user/manual/en/setting-up/articles/edit-submitted-document.md

Changes in line with https://github.com/frappe/erpnext_documentation/pull/15

chore: fix grammar for Editing a submitted document

---

erpnext_documentation/www/docs/user/manual/en/customize-erpnext/articles/dynamic-link-fields.md

docs: fixing rogue div and header formatting

---

README.md

Update license for documentation content, as per https://erpnext.com/license-trademark#license

chore: update docs content license

---

erpnext_documentation/www/docs/user/manual/en/introduction/index.md

Replace old video with:
https://www.youtube.com/watch?v=j60xyNFqX_A

chore: update getting started video

---

erpnext_documentation/www/docs/user/manual/en/CRM/appointment.md

**Appointment Booking Settings** broken link on https://docs.erpnext.com/docs/user/manual/en/CRM/appointment

fix: broken link Appointment Booking Settings

---

erpnext_documentation/www/docs/user/manual/en/buying/purchase-order.md
erpnext_documentation/www/docs/user/manual/en/stock/delivery-note.md
erpnext_documentation/www/docs/user/manual/en/stock/material-request.md
erpnext_documentation/www/docs/user/manual/en/stock/purchase-receipt.md

- Added Scan Barcode details
- Removed trailing white space

docs: Added missing 'Scan Barcode' to docs

---

erpnext_documentation/www/docs/user/manual/en/customize-erpnext/articles/field-types.md

Feature PR: https://github.com/frappe/frappe/pull/9784
Port of https://github.com/frappe/erpnext_com/pull/766

feat: Email and Phone number validations on Data fieldtype

---

erpnext_documentation/www/docs/user/manual/en/projects/project-update.md

docs: project update typo fix

---

erpnext_documentation/www/docs/user/manual/en/customize-erpnext/custom-field.md
erpnext_documentation/www/docs/user/manual/en/customize-erpnext/customize-form.md

docs: documentation for link preview popover

---

erpnext_documentation/www/docs/user/manual/en/customize-erpnext/authorization-rule.md

typo fixes, fixed grammatical errors and other mistakes

docs: update authorization rule

---

erpnext_documentation/www/docs/user/manual/en/setting-up/sms-setting.md

fixed:
1. Changed  an -->a
2. Changed a sentence for better understanding.

docs: update settings up SMS

---

erpnext_documentation/www/docs/user/manual/en/CRM/campaign.md
erpnext_documentation/www/docs/user/manual/en/CRM/email-campaign.md
erpnext_documentation/www/docs/user/manual/en/CRM/linkedin-settings.md
erpnext_documentation/www/docs/user/manual/en/CRM/social-media-post.md
erpnext_documentation/www/docs/user/manual/en/CRM/twitter-settings.md

**Added new card in CRM desk**
**Added Twitter and LinkedIn link in Setting Card**

Changing navigation in Campaign, Email Campaign, Social Media Post

---

erpnext_documentation/www/docs/user/manual/en/CRM/contents.md
erpnext_documentation/www/docs/user/manual/en/CRM/linkedin-settings.md
erpnext_documentation/www/docs/user/manual/en/CRM/social-media-post.md
erpnext_documentation/www/docs/user/manual/en/CRM/twitter-settings.md

*   fix links for campaign
*   add social media post and setup to contents page

fix: Social Media Post docs

---

erpnext_documentation/www/docs/user/manual/de/customize-erpnext/print-format.md

- Highlight code sample correctly.
- Improve code sample.
- Remove old paragraph stating that footers are not possible.

fix(german): Improve code sample

---

erpnext_documentation/www/docs/user/manual/en/healthcare/clinical_procedure.md
erpnext_documentation/www/docs/user/manual/en/healthcare/clinical_procedure_template.md
erpnext_documentation/www/docs/user/manual/en/healthcare/contents.md
erpnext_documentation/www/docs/user/manual/en/healthcare/fee_validity.md
erpnext_documentation/www/docs/user/manual/en/healthcare/healthcare_practitioner.md
erpnext_documentation/www/docs/user/manual/en/healthcare/patient.md
erpnext_documentation/www/docs/user/manual/en/healthcare/patient_appointment.md
erpnext_documentation/www/docs/user/manual/en/healthcare/patient_encounter.md
erpnext_documentation/www/docs/user/manual/en/healthcare/practitioner_schedule.md
erpnext_documentation/www/docs/user/manual/en/healthcare/prescription_dosage_and_duration.md
erpnext_documentation/www/docs/user/manual/en/healthcare/vital_signs.md

- fix broken links in healthcare
- add a link for the practitioner schedule to contents.

fix: broken links in Healthcare docs

---

erpnext_documentation/www/docs/user/manual/en/customize-erpnext/server-script.md

No description for sites hosted on erpnext.com

Added description

---

erpnext_documentation/www/docs/user/manual/en/stock/articles/stock-entry-purpose.md

Fix line 8 typo for the word 'deducated'

fix: deducted type

---

.deploy/build/erpnext-docs-nginx/Dockerfile
.deploy/build/erpnext-docs-nginx/install_app.sh
.deploy/build/erpnext-docs-worker/Dockerfile
.travis.yml
spell_checker/cSpell.json

feat: auto-deploy docs using travis

---

.travis.yml

build: move deploy from after_success to stage

---

erpnext_documentation/www/docs/assets/css/docs-erp.css
erpnext_documentation/www/docs/user/manual/en/setting-up/workflows.md

Docs for Allow Workflow Checkbox.
PR in Frappe:
https://github.com/frappe/frappe/pull/10806

docs: Allow Workflow checkbox in DocType

---

erpnext_documentation/www/docs/assets/css/docs-erp.css
erpnext_documentation/www/docs/user/manual/en/setting-up/workflows.md

Reverts frappe/erpnext_documentation#108

fix: Revert Allow Workflow checkbox in DocType

---

erpnext_documentation/www/docs/user/manual/en/accounts/opening-balance/capital_accounts.md

changed spelling of Accouns to Accounts

docs: Fix spelling of Accounts in Capital Accounts

---

erpnext_documentation/www/docs/user/manual/en/CRM/twitter-settings.md

Changed from LinkedIn to Twitter

fix: Twitter typo fix

---

erpnext_documentation/www/docs/user/manual/en/customize-erpnext/server-script.md

Docs for changes introduced in https://github.com/frappe/frappe/pull/11260

feat: add print and attach_print

---

erpnext_documentation/www/docs/user/manual/en/using-erpnext/restore-deleted-docs.md

documentation for https://github.com/frappe/frappe/pull/10923

docs(Deleted Document): File trashing

---

erpnext_documentation/www/docs/user/manual/en/projects/project.md

Task weightage Calculation note shifted to proper section

Task weightage Calculation note shifted

---

erpnext_documentation/www/docs/user/manual/en/using-erpnext/restore-deleted-docs.md

Reverts frappe/erpnext_documentation#116
feat canceled

Revert "docs(Deleted Document): File trashing"

---

erpnext_documentation/www/docs/user/manual/en/using-erpnext/video.md

Revisions on https://github.com/frappe/erpnext_documentation/pull/153

fix: (minor) Restructuring Video Documentation

---

erpnext_documentation/www/docs/user/manual/en/CRM/social-media-post.md

fix: social media post version label

---

erpnext_documentation/www/docs/user/manual/en/website/website-settings.md

section 10 in website settings

neutralize gender in website setting 

---

erpnext_documentation/www/docs/user/manual/en/CRM/contents.md

update CRM index

---

erpnext_documentation/www/docs/user/manual/en/website/website-settings.md

Docs for https://github.com/frappe/frappe/pull/11594

docs: Website Settings "Google Analytics Anonymize IP"

---

erpnext_documentation/www/docs/user/manual/en/stock/articles/material-transfer-from-delivery-note.md

docs: fix broken image

---

erpnext_documentation/www/docs/user/manual/en/stock/articles/material-transfer-from-delivery-note.md

chnage.png to .gif in image path

docs: fix image name

---

erpnext_documentation/www/docs/user/manual/en/setting-up/settings/system-settings.md

Reference: https://github.com/frappe/frappe/pull/12014

docs(System Settings): Option to remove exif data from images

---

erpnext_documentation/www/docs/user/manual/en/setting-up/email/email-template.md

Frappe PR: [frappe/12018](https://github.com/frappe/frappe/pull/12018)

chore: add docs for Use HTML check

---

erpnext_documentation/www/docs/user/manual/en/customize-erpnext/server-script.md

docs: Permissions Query in Server Script

---

erpnext_documentation/www/docs/user/manual/en/regional/india/setup-e-invoicing.md

fix: context to ewaybill and pricing

---

erpnext_documentation/www/docs/user/manual/en/education/lms-masters.md

removed .md extension on the link

Corrected link to topics

---

erpnext_documentation/www/docs/user/manual/en/setting-up/workflows.md

Included version 13 allowed functions, including date/time functions.
Feature #11745

feat: Updated workflow.md to v13

---

erpnext_documentation/www/docs/user/manual/en/accounts/purchase-invoice.md

Fix minor errors in purchase invoice documentation.

docs(accounting): Fix typo in purchase-invoice.md

---

erpnext_documentation/www/docs/user/manual/en/regional/germany/datev-export.md
erpnext_documentation/www/docs/user/manual/en/regional/germany/datev-settings.md

Docs for https://github.com/frappe/erpnext/pull/24086

docs: temporary against account

---

erpnext_documentation/www/docs/user/manual/en/customize-erpnext/contents.md

Fixed punctuation in customize-erpnext contents

docs: Minor fixes in customize-erpnext contents

---

erpnext_documentation/www/docs/user/manual/en/using-erpnext/articles/renaming-documents.md

Fixing broken link for erpnext_documentation

docs(renaming-documents.md): Fix broken link

---

erpnext_documentation/www/docs/user/manual/en/accounts/subscription.md

docs: information for subscription early invoice.

---

erpnext_documentation/www/docs/user/manual/en/setting-up/workflows.md

Previous Workflow Document statuses: Saved = 0, Submitted = 1, **Cancelled = 3**
**Updated ** Workflow Document statuses: Saved = 0, Submitted = 1, **Cancelled = 2**

Improved the doc status of the 'cancelled document' in workflow from '3' to '2'

---

erpnext_documentation/www/docs/user/manual/en/accounts/accounts-settings.md
erpnext_documentation/www/docs/user/manual/en/stock/stock-settings.md

doc for PR : https://github.com/frappe/erpnext/pull/24854

docs: Role to allow over billing, delivery, receipt

---

erpnext_documentation/www/docs/user/manual/en/buying/buying-settings.md
erpnext_documentation/www/docs/user/manual/en/selling/selling-settings.md

Docs for PR: https://github.com/frappe/erpnext/pull/24852

docs: configurable action if the same purchase/selling rate is not maintained

---

erpnext_documentation/www/docs/user/manual/en/customize-erpnext/customize-form.md
erpnext_documentation/www/docs/user/manual/en/setting-up/email/email-template.md
erpnext_documentation/www/docs/user/manual/en/setting-up/email/sending-email.md

Docs for https://github.com/frappe/frappe/pull/12264

docs: Default Email Template

---

erpnext_documentation/www/docs/user/manual/en/accounts/process-statement-of-accounts.md
erpnext_documentation/www/docs/user/manual/en/regional/germany/datev-export.md
erpnext_documentation/www/docs/user/manual/en/stock/articles/material-transfer-from-delivery-note.md
erpnext_documentation/www/docs/user/manual/en/using-erpnext/save-filter.md

#263 fixed one broken link that was pointing to .md file, there were other similar broken links.

fix: broken links pointing to .md files

---

erpnext_documentation/www/docs/user/manual/en/introduction/the-champion.md

Updated the Champion page with a description of what project champions do and what skills they should have.

docs: Updated Champion Page

---

erpnext_documentation/www/docs/user/manual/en/introduction/index.md

Current content positions ERPNext as though it's exclusively targeted towards SMEs. Updated it to reflect the maturity. Also provided some historical context on the origin of the term 'ERP'.

docs: Updated Introduction Page

---

erpnext_documentation/www/docs/user/manual/en/introduction/implementation-strategy.md

Updated with links and edited for clarity.

docs: Updated Implementation Strategy

---

erpnext_documentation/www/docs/user/manual/en/projects/project.md

- Fixed task weight formula
- Fixed task weight example calculation
- Fixed total weight of tasks in note

fix: Task Weight Formula, Calculation and Note

---

erpnext_documentation/www/docs/user/manual/en/manufacturing/contents.md
erpnext_documentation/www/docs/user/manual/en/manufacturing/reports/quality-inspection-summary.md

- renamed Inspection Summary file
- fixed spelling mistakes within the file
Signed-off-by: Shreyansh Jain <ithead@ambibuzz.com>

fix: incorrect spelling of Inspection Summary Report

---

erpnext_documentation/www/docs/user/manual/en/customize-erpnext/articles/field-types.md

docs: Update Data field type docs

---

erpnext_documentation/www/docs/user/manual/en/regional/germany/datev-export.md

Add info about debtor/creditor number and billing address.
Docs for https://github.com/frappe/erpnext/pull/25238

docs: datev export

---

erpnext_documentation/www/docs/user/manual/en/projects/profitability.md
erpnext_documentation/www/docs/user/manual/en/projects/project-profitability-report.md

docs: profitability report

---

erpnext_documentation/www/docs/user/manual/en/manufacturing/routing.md

- Added a note for changing operation time in routing.

docs: added a note for updating operation time in routing

---

erpnext_documentation/www/docs/user/manual/en/human-resources/employee.md

docs for PR: https://github.com/frappe/erpnext/pull/26027

docs: add Inactive status to Employee

---

erpnext_documentation/www/docs/v13/user/manual/en/customize-erpnext/index.html

- Remove the `Custom Script` card (which was broken)
- Add the new `Client Script` card
(Applicable for v13)

docs: replace card `Custom Script` with `Client Script` in `Customize ERPNext` section

---

erpnext_documentation/www/docs/v13/user/manual/en/website/web-form.md

The url was broken and was redirecting to 404 page in MDN website.

docs: Fix broken url

---

erpnext_documentation/www/docs/v13/user/manual/en/setting-up/notifications.md

depends on https://github.com/frappe/frappe/pull/13206

feat: hide link button from slack notifications
